### ISSUE TITLE
incorrect balance after transaction

### ISSUE THREAD

**Issue by relikd** [strichliste/strichliste-backend#47]
After a couple of transactions and undos the account balance shows +1 € instead of 0 €. 

![screenshot](https://user-images.githubusercontent.com/1321720/52902544-5f3acd00-3212-11e9-85cc-47e7d8246f77.png)

```
sqlite> select * from user where id = 2;
2|Oliver||100|0|2019-02-16 15:08:44|2019-02-16 16:08:21

sqlite> select * from transactions where user_id = 2;
1|2||||||1000|0|2019-02-16 15:08:57
2|2||||||-1000|0|2019-02-16 15:09:00
12|2|1|||1||-100|1|2019-02-16 16:08:09
13|2|1|||1||-100|1|2019-02-16 16:08:15
```

This may be relevant: 
- I am running Strichliste on a Raspberry Pi Zero W (with slow response times, sometimes in the seconds).
- sqlite db, since only three users will use it

Also, you should change the cursor icon for article buttons. Currently it is not apparent that the button is clickable.

**Comment by schinken** [comment]
Hi! Thanks for the bug report. I will look into it

Which Database are you using? The only case where I can image this happens is with sqlite, because the database does not support the required transactional feature

**Comment by schinken** [comment]
aaah sorry. I should have looked first. You're using sqlite. Dang. 
Jeah this can only happen with sqlite. 

As the website states, you should _not_ use sqlite ;)
https://www.strichliste.org/install/

I'm also going to change the default .env file
