### ISSUE TITLE
Feature Request: Ability to add paypal.me links to users

### ISSUE THREAD

**Issue by CptPie** [strichliste/strichliste-backend#48]
For our usecases (one user orders food and others pay via strichliste or paypal) it would be nice to be able to pay other users of strichliste via paypal inside the strichliste overview.

**Comment by schinken** [comment]
Thats actually possible! 
You can go to the specific user page: https://demo.strichliste.org/#!/user/16 and use the paypal option

It has to be configured in the backend, and documentation is still missing - but it's there :)

**Comment by CptPie** [comment]
Well - then get the documentation written :)

**Comment by schinken** [comment]
See #46
