### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by kmille** [strichliste/strichliste-backend#53]
Hey, I end up in a redirect loop which mackes the Strichliste not usable any more. Steps to reproduce:

1. Go to /index.html
2. Click on 'Article List'
3. The loop begins. The requests are (all called via ajax/xmlhttprequest or javascript library):
	- /api/article?limit=999 returns 200
		{"count":5,"articles":[{"id":1,"name":"Classic Mate","barcode":null,"amount":100,"isActive":true,"usageCount":1,"precursor":null,"created":"2019-01-21 19:12:49"},{"id":2,"name":"Flora Mate","barcode":null,"amount":150,"isActive":true,"usageCount":7,"precursor":null,"created":"2019-01-21 19:13:15"},{"id":5,"name":"Gro\u00dfer Snack","barcode":null,"amount":100,"isActive":true,"usageCount":0,"precursor":null,"created":"2019-01-21 19:14:24"},{"id":3,"name":"Kleiner Snack","barcode":null,"amount":30,"isActive":true,"usageCount":8,"precursor":null,"created":"2019-01-21 19:13:39"},{"id":4,"name":"Mittlerer Snack","barcode":null,"amount":50,"isActive":true,"usageCount":5,"precursor":null,"created":"2019-01-21 19:14:06"}]}
	- /api/user?deleted=false returns 200
		{"users":[{"id":36,"name":.... 
	- /api/user?deleted=false returns 200
		{"users":[{"id":36,"name":.... 
	- /api/user?deleted=false returns 200
		{"users":[{"id":36,"name":.... 
	- Welcome to the loop

Sometimes I can stop the loop clicking on 'Split invoice'... We are using PHP 7.3 on Debian 9.6 with Strichliste v1.6.2 from the mixed repo (https://github.com/strichliste/strichliste). If you need any further infos don't hesitate to ask.

Thanks in advance

kmille

**Comment by schinken** [comment]
Please check for `idleTimer` in your `strichliste.yaml` file. It should be named `idleTimeout`
After that just do a `APP_ENV=prod php bin/console cache:clear`

It was a breaking change in the config because of some misunderstandings between me and the frontend dev. Sorry about that

**Comment by kmille** [comment]
Thanks! Worked for me!
