### ISSUE TITLE
Mit uns Mate trinken

### ISSUE THREAD

**Issue by DO1JLR** [strichliste/strichliste-backend#55]
Hey @schinken 

Vielen Dank für deine Strichliste.
Sie wird bei uns in der @toolboxbodensee fleißig eingesetzt.

Als Dankeschön haben wir dir dort auc schon einen Account eingerichtet:

![IMG_20190521_231733](https://user-images.githubusercontent.com/16953664/58131566-4b42a500-7c1f-11e9-8f03-acd3bdde0922.jpg)

Komm doch mal auf eine Mate vorbei.
Jeden Donnerstag und meistens auch am Wochenende sind wir da!

https://toolbox-bodensee.de/kontakt/

**Comment by schinken** [comment]
Vielen Dank! :) Vielleicht mach ich tatsächlich Urlaub am Bodensee und schau bei euch vorbei.
Freut mich, dass euch strichliste gefällt. Wenn ihr Featurewünsche habt oder kommentare zu den bestehenden Tickets, immer gerne her damit :)

**Comment by schinken** [comment]
Gerne könnt ihr auch einen Pull-Request machen, um euch zur Homepage hinzuzufügen:
https://github.com/strichliste/homepage/blob/master/data/users.toml
