### ISSUE TITLE
Oops two error messages

### ISSUE THREAD

**Issue by STCsabo** [strichliste/strichliste-backend#82]
Hi,

after the installation [Release v1.8.2] according to the instructions I can't do anything, I always get the two error messages.

Oops could not create this user
Oops could not load users :-( Maybe check your internet connection and try it again

I'm a bit at the end of my Latin

Server-Version: 10.11.8-MariaDB -> Connection works when I look with phpMyAdmin three tables are created. article, transactions, user
PHP version 8.3.10
Server version: Apache/2.4.58 (Ubuntu)

Would be nice if you could give me a tip.

THX Sabo

**Comment by schinken** [comment]
What was the issue ? ;) i'm curious

**Comment by STCsabo** [comment]
The problem persists and I don't know what to do. Is there an admin
interface? How do I create an admin? I can't seem to find anything about
it. :(

https://strichliste.svreudern.de

Grüße Dennis

Christopher Schirner ***@***.***> schrieb am Di., 13. Aug.
2024, 17:39:

**Comment by schinken** [comment]
Hey Dennis. Schreib mir mal an christopher [at] schirner.org. Dann schau ich mir das mit an. 
Wenn wir den fehler haben können wir ja auch die doku anpassen

**Comment by STCsabo** [comment]
Hi super,

Ich schrieb dir morgen was ich genau gemacht habe.

Grüße und danke 😊👋

Christopher Schirner ***@***.***> schrieb am Di., 13. Aug.
2024, 21:13:

**Comment by schinken** [comment]
aye!

**Comment by sandos187** [comment]
Hi there,

i would be interested in what was the problem here, because i'm face the same problem

Thx
Sandos

**Comment by STCsabo** [comment]
Hi,

Could you please describe in more detail what exactly the problem is?
What error message are you getting, and what is currently not working as expected?

With a bit more information, I may be able to help you.

Best regards,

Dennis

**Comment by sandos187** [comment]
Hi,
sure, my bad.
I'm trying to install Strichliste on an uberspace astroid (https://uberspace.de).
Created the database and deployed the scheme as mentioned in the installation guide. All three tables were created, so database-connection from commandline is working.
Frontend loads and is shown, but i get those "Oops"-Messages mentioned above when jumping between the tabs or try creating users or articles.

I know "github issues" aren't a support forum, but couldn't find you on the mentioned IRC server.

Sandos

**Comment by STCsabo** [comment]
Hi,

as far as I know, Strichliste is not primarily intended to be installed on a publicly accessible domain — at least not without proper password protection.

In my case, I believe the issue was solved by creating the following file in the public directory and adapting it accordingly:

https://github.com/strichliste/strichliste-backend/blob/master/public/.htaccess.example

After creating and configuring the .htaccess file properly, it started working.

Maybe this helps in your case.

Best regards,

Dennis

**Comment by sandos187** [comment]
Wow, that was easy. Thank you very much that helped.
